spring:
  application:
    name: external
  config:
    import: optional:configserver:http://localhost:9090

server:
  port: 9090

# Eureka registration
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

